# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-test-simple
version    : '1.302219'
release    : 15
source     :
    - https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Test-Simple-1.302219.tar.gz : 420600911230de768427f6646758d89b6c07977b565e5b40118e5b8440dbb30b
homepage   : https://metacpan.org/pod/Test::Simple
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test2 - Framework for writing test tools that all work together.
description: |
    Test2 is a new testing framework produced by forking Test::Builder, completely refactoring it, adding many new features and capabilities.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
